[versions]
agp = "8.7.2"
kotlin = "1.9.24"

coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
navigationUiKtx = "2.8.8"
permissionx = "1.7.1"
preferenceKtx = "1.2.1"
roomVersion = "2.6.1"
workerVersion = "2.10.0"
espressoCore = "3.5.1"
androidxPagingRuntimeKtx = "3.3.2"
hiltVersion = "2.51.1"
annotation = "1.9.1"
gson = "2.10"

xpopup = "2.10.0"
coil = "2.6.0"
androidLogger = "v2.2.1"
customactivityoncrash = "2.4.0"
shapeview = "9.2"
utilcodex = "1.31.1"

[libraries]
android-logger = { module = "com.github.journe:Android-logger", version.ref = "androidLogger" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidxPagingRuntimeKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-worker = { module = "androidx.work:work-runtime-ktx", version.ref = "workerVersion" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
customactivityoncrash = { module = "cat.ereza:customactivityoncrash", version.ref = "customactivityoncrash" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
shapeview = { module = "com.github.getActivity:ShapeView", version.ref = "shapeview" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }
xpopup = { module = "com.github.li-xiaojun:XPopup", version.ref = "xpopup" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

